### ISSUE TITLE
WKT fails to parse

### ISSUE THREAD

**Issue by DanielCeregatti** [arenevier/gisconverter.php#1]
Hi,

I recently added your gisconverter.php to some code I'm working on, as I need to convert WKT to GeoJSON. It was working well at first, properly parsing several geometries from my TIGER based PostGIS database, until I ran into this:

http://98.154.186.14/test.php

Please read the comments in the source code of the script:

http://98.154.186.14/test.phps

It seems to fail parsing this rather large geometry that I'm getting from my database. This geometry is a MULTIPOLYGON of the state of California, USA, as returned by my database. According to PostGIS, this is a valid geometry.

Thanks,

Daniel

**Comment by arenevier** [comment]
looks like there is a bug in php
$compstr = preg_replace('/^\s_(?(._?))?\s*$/', '$1', $compstr);

fails with long strings (> 2^16)
but I removing spaces at start and end of string was not needed since it had already been trimmed. So, now, the regexp is more efficient and also should work with long strings. Daniel, can you try my last push and confirm if it works for you ?

**Comment by DanielCeregatti** [comment]
It's working now for every geometry where it was failing before except for the one in the example in my bug report. This is by far the largest geometry I've tested. The URL I mentioned in the original bug now uses your latest gisconverter.php, but still shows the bug. I've added a symlink to http://98.154.186.14/gisconverter.phps so you can verify that I'm using the latest version, albeit with a modification. I've removed all calls to json_encode(), as I need to wrap the GeoJSON inside of other JSON, which is encoded later in the code. Perhaps this can be a feature?

Daniel

**Comment by arenevier** [comment]
Hi daniel
does it work now with my latest code push.
about the json_encode, I probably need to think about a way to get a geometry php object.

**Comment by DanielCeregatti** [comment]
It works beautifully now! Thanks!

Regarding json_encode, all I did was change the 3 lines that looked like this:

return json_encode($value);

to this:

return $value;

Considering JSON doesn't care about object types, it worked as I expected it would.

Daniel
