### ISSUE TITLE
Collboration

### ISSUE THREAD

**Issue by phayes** [arenevier/gisconverter.php#2]
Howdy,

I thought I would just send you a message and let you know what I'm up to over at https://github.com/phayes/geoPHP . It looks like we have very similar projects tackling similar functionality.  I would like to see if there is any way we can collaborate.

If you don't mind, I'm going to scoop some of your KML and GPX code. I would invite you to do the same if any of my project looks useful. We are both BSD, so the licensing is compatible. I'll add your name to the files where I include your stuff.

Looking forward to seeing how we can collaborate. At the very least code-swapping might be useful, but perhaps there are some deeper ways we can work together.

Thanks!

~ Patrick Hayes

**Comment by arenevier** [comment]
Le samedi 19 mars 2011, à 15:35:08 -0700, phayes a écrit : 

> Howdy,
> 
> I thought I would just send you a message and let you know what I'm up to over at https://github.com/phayes/geoPHP . It looks like we have very similar projects tackling similar functionality.  I would like to see if there is any way we can collaborate.
> 
> If you don't mind, I'm going to scoop some of your KML and GPX code. I would invite you to do the same if any of my project looks useful. We are both BSD, so the licensing is compatible. I'll add your name to the files where I include your stuff.
> 
> Looking forward to seeing how we can collaborate. At the very least code-swapping might be useful, but perhaps there are some deeper ways we can work together.
> 
> Thanks!

Hi,
I'm very glad you find my project useful :)

The goal of my project is "only" to make a geometry converter. If I understand 
correctly, you want to have a more comprehensive geometry stack. Currently, I 
also don't known how those projects would interact, but sure, I will at least 
pick some code from your project when I need to.

Also, please note, I use php5.3 for my project using gisconverter. So, I use 
some php5.3 features in gisconverter. If you want to target php5.2 and below, 
you may need to make some small changes from my code. Mainly, removing lambda 
functions from array_\* functions, and removing static:: to use CLASSNAME:: 

regards
arno

**Comment by phayes** [comment]
Fantastic. Well, I'm watching your project and may borrow code from time to time. Good luck!
