### ISSUE TITLE
BSD / GPL license for geoPHP

### ISSUE THREAD

**Issue by phayes** [arenevier/gisconverter.php#3]
Hi!

As you know I've used some of your code over in geoPHP (https://github.com/phayes/geoPHP) in our KML adapter. It has been extensively modified since then, but it is derived from your work here. There's an issue open on my issue-queue here (https://github.com/phayes/geoPHP/issues/15) asking if I could dual-license geoPHP as both BSD and GPL.  

So my question is, may I have your permission to dual-license geoPHP as both BSD and GPL? I need to ask you since some of the code is derived from your work here. Note that I'm not asking you to-relicense gisconverter.php, but merely to allow me to dual license geoPHP.

Thank you for your consideration.

~Patrick Hayes

**Comment by arenevier** [comment]
Yes, you can dual-license geoPHP.
No problem.

**Comment by phayes** [comment]
Thanks!
